### ISSUE TITLE
Question about condition_row in GradientDescent

### ISSUE THREAD

**Issue by diegogcerdas** [webis-de/arxiv23-prompt-embedding-manipulation#4]
Hello, thank you for this great work!

I wanted to ask what is the intuition behind using `condition_row` in [get_text_embedding](https://github.com/webis-de/arxiv23-prompt-embedding-manipulation/blob/8e41100c1fb358a28aa838b0b128380ab5a0cc10/metric_based_optimization/full_pipeline_descent.py#L75C9-L75C27) as opposed to, e.g., using the whole `uncondition`.

Thank you!

**Comment by niklasdeckers** [comment]
Hello,

the CLIP embedding of the 0th token is always the same. We observed that Stable Diffusion relies on this and produces worse images otherwise. Thus, it didn't make sense to optimize the embedding of the 0th token. We construct the `condition` by first splitting the 0th token embedding; only the left-over part is then declared as a trainable variable (`torch.nn.Parameter`):
```
        self.condition_row = condition[:, 0, :]
        self.condition = torch.nn.Parameter(condition[:, 1:, :])
```
We then stitch these parts back together in `get_text_embedding`. The `uncondition` works the same way.
